#include <iostream>
#include <exception>
using namespace std;

int main() 
{
	
}